name: 'Prepare Build'
description: 'Prepares the checkout for compilation'
inputs:
  solution:  # id of input
    description: 'The solution to perform the package restore against.'
    required: true
    default: '*.sln'
outputs:
  version:
    description: "GitVersion output for the current build."
    value: ${{ steps.gitversion.outputs.NuGetVersionV2 }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.8.2'
    - name: Check dotnet installation
      run: ls /usr/share/dotnet/sdk
      shell: bash
    - name: Restore Packages
      run: dotnet restore ${{ inputs.solution }}
      shell: bash
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15
      with:
        useConfigFile: true
    - uses: actions/upload-artifact@master
      with:
        name: workspace
        path: .
        retention-days: 1
