name: 'Prepare Build'
description: 'Prepares the checkout for compilation'
inputs:
  solution:  # id of input
    description: 'The solution to perform the package restore against.'
    required: true
    default: '*.sln'
  upload-artifact:
    description: 'Upload a workspace artifact at the end.'
    required: false
    default: 'true'
outputs:
  version:
    description: "GitVersion output for the current build."
    value: ${{ steps.gitversion.outputs.SemVer }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x
          8.x
          9.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.1
      with:
        versionSpec: '6.3.0'
    - name: Restore Packages
      run: dotnet restore ${{ inputs.solution }}
      shell: bash
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.1.1
      with:
        useConfigFile: true
    - uses: actions/upload-artifact@master
      if: ${{ inputs.upload-artifact == 'true' }}
      with:
        name: workspace
        path: .
        retention-days: 1
